# This sample requires an LVM VG with the name of `cinder-volumes` to exist on the OpenShift node where cinder-volume runs
# It also requires that nvme-fabrics kernel module is running everywhere and that nvmet is running on the controller host
# The correct way to configure the load of additional kernel modules is using `MachineConfig` as shown in `nvme-fabrics.yaml`.yaml`.
# To create the LVM on CRC the sample also uses a `MachineConfig` using a systemd unit with file `lvm.yaml`
#
# ATTENTION: After applying this OpenShift nodes will reboot, because of the `MachineConfig` changes and will take a while to recover.

resources:
  # Whole OpenStack deployment using a Cinder NVMe-TCP LVM backend
  # - https://github.com/openstack-k8s-operators/cinder-operator/tree/main/config/samples/backends/lvm/nvme-tcp
  # For testing we can use our own repo and branch instead
  - https://github.com/Akrog/cinder-operator//config/samples/backends/lvm/nvme-tcp?ref=more-backend-samples
components:
  - ../glance-common
