# Define the "osp-glance-cinder-secret" Secret that contains sensitive
# information pertaining to the cinder backend
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: glance
  name: osp-glance-cinder-secret
type: Opaque
stringData:
  cinder-secrets.conf: |
    [default_backend]
    cinder_store_user_name = glance
    cinder_store_password = 12345678
    cinder_store_project_name = service
